spring.application.name=bibliotecadigital
server.port=8080

# ==========================================
# Configuração SQL SERVER (CONEXÃO DIRETA)
# ==========================================
# Usando 127.0.0.1 para evitar problemas de resolução de nome
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=bibliotecadigital;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=biblioteca2026
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Forçando o Dialeto para evitar erro de Metadata
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
